### ISSUE TITLE
Output to PostgreSQL by Embulk

### ISSUE THREAD

**Issue by masayuki14** [masayuki14/worklog#5]
embulk の出力先をPostgreSQLにする。
PostgreSQLはDockerコンテナにして動くようにする。

**Comment by masayuki14** [comment]
dealcoach を参考に `docker-compose.yml` を作る

```yaml
version: '3'
services:
  embulk:
    build: .
    volumes:
      - .:/work
    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    image: postgres:9.6
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB:       interest_tier3
      POSTGRES_USER:     tier3
      POSTGRES_PASSWORD: password
```

embluk の Dockerfile はそのまま使える。
